version: '3'

services:
  bank:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank:1.0
    container_name: bankyorik
    restart: always
    ports:
      - "8080:8080"

  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"