version: '3'

services:
  bank:
    build:
      context: .
      dockerfile: Dockerfile
    image: bank:1.0
    container_name: bankyorik
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: